<div style="text-align:center;color:#888888;"><h2> IMP 5004 - Python Programming for Intelligent Medicine </h2></div>
<div style="text-align:center;"><h1> Final Exam (110-1) - Solution </h1></div>

* Exam date: 2022/01/06 9:10-12:10
* There are 8 questions, 110 points in total.
* Open everything including the Internet. Feel free to import any package you need.
* "Cheating" is basically coordinating with others. So don't do that.
* When you find necessary to raise an exception, please include a meaningful error message to indicate what the source of the error is.

In [24]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [25]:
from IPython.display import Image
%matplotlib inline

In [26]:
import numpy as np
import os
import pandas as pd

In [27]:
df = pd.read_csv("data/iris.csv", index_col=False)

### <span style="color:red">Question 1:</span> Dataframe setting column name (5 pts)

Please read the file `iris_data.npy` into a data frame, with the names of the columns being *sepallength*, *sepalwidth*, *petallength*, *petalwidth*, *species*, respectively.

<span style="color:green"> <b>Examples:</b></span>
```python
df = Q1('iris_data.npy')
df.head()
```
Should result in
<img src="img/iris_dataframe_raw.png" style="height: 150px; "/>

In [28]:
# Please write your code here. Remember to remove the pass statement.
def Q1(df):
    df = pd.read_csv("data/iris.csv", index_col=False)
    pd.DataFrame(df, columns=['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])

In [29]:
df = pd.read_csv("data/Q1.csv")
df.head()

sepallength  sepalwidth  petallength  petalwidth      species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

### <span style="color:red">Question 2:</span> Show data summary (10 pts)

Print out information including
* count
* mean
* std (standard deviation)
* min
* The 12.5th, 25th, 50th, 75th, 87.5th percentiles
* max

for all the features (sepallength, sepalwidth, petallength, petalwidth) in iris dataset.

(Percentile definition: https://en.wikipedia.org/wiki/Percentile)

<span style="color:green"> <b>Reference Output:</b></span>
<img src="img/iris_summary.png" style="height: 250px; "/>

In [30]:
# Please write your code here
# Reference: https://vimsky.com/zh-tw/examples/usage/python-pandas-dataframe-describe-method.html
perc = [0.125,0.25,0.50,0.75,0.875]
df.describe(percentiles = perc)

sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
12.5%     4.900000    2.562500     1.400000    0.200000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
87.5%     6.800000    3.500000     5.637500    2.100000
max       7.900000    4.400000     6.900000    2.500000

### <span style="color:red">Question 3:</span> Filter a dataframe with multiple conditions (10 pts)
Filter the rows that has *sepalwidth* > 2.1 and *petallength* < 1.4.

<span style="color:green"> <b>Reference Output:</b></span>
<img src="img/row_selection.png" style="height: 250px; "/>

In [31]:
# Please write your code here
sepalwidth = df['sepalwidth']
petallength = df['petallength']
df[sepalwidth > 2.1][petallength < 1.4]

<ipython-input-31-2b1f0901f342>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[sepalwidth > 2.1][petallength < 1.4]


sepallength  sepalwidth  petallength  petalwidth      species
2           4.7         3.2          1.3         0.2  Iris-setosa
13          4.3         3.0          1.1         0.1  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
16          5.4         3.9          1.3         0.4  Iris-setosa
22          4.6         3.6          1.0         0.2  Iris-setosa
35          5.0         3.2          1.2         0.2  Iris-setosa
36          5.5         3.5          1.3         0.2  Iris-setosa
38          4.4         3.0          1.3         0.2  Iris-setosa
40          5.0         3.5          1.3         0.3  Iris-setosa
41          4.5         2.3          1.3         0.3  Iris-setosa
42          4.4         3.2          1.3         0.2  Iris-setosa

### <span style="color:red">Question 4:</span> Find correlations between features (10 pts)

Find the correlation between *sepalwidth* and *petallength*.

<span style="color:green"> <b>Reference Output:</b></span>
```python
-0.42051609640115445
```

In [32]:
# Please write your code here
df['sepalwidth'].corr(df['petallength'])

-0.42051609640115445

### <span style="color:red">Question 5:</span> Linear regression (15 pts)

Fit a linear regression function that predicts *petallength* from *sepallength*	and *petalwidth*.  The regression function takes the form

$$y = w_0 x_0 + w_1 x_1 + b$$

where $x_0$ is the *sepallength* and $x_1$ is the *petalwidth*, and $y$ is the estimated *petallength*.  Report $w_0$, $w_1$, $b$, as well as the $R^2$-value.

<span style="color:green"> <b>Examples:</b></span>
```python
R_sqr, w, b = Q5()
print(f'y = {w[0]:.3f} x0 + {w[1]:.3f} x1 + {b:.3f}')
print(f'R square = {R_sqr:.3f}')
```
Should result in
```python
y = 0.543 x0 + 1.744 x1 + -1.502
R square = 0.948
```

In [33]:
# Please write your code here. Remember to remove the pass statement.
# https://towardsdatascience.com/linear-regressions-with-scikitlearn-a5d54efe898f
def Q5():
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression
    x0 = df['sepalwidth'].values.reshape(-1,1)
    x1 = df['petallength'].values.reshape(-1,1)
    x_train, x_test, y_train, y_test = train_test_split(x0,x1,test_size=0.2,random_state=1)
    linreg = LinearRegression().fit(x_train,y_train)
    print('b =',linreg.intercept_)
    print('R_train =',linreg.score(x_train,y_train))
    print('R_test =',linreg.score(x_test,y_test))
Q5()

b = [8.78937886]
R_train = 0.15117975352646185
R_test = 0.26791188864550297


In [34]:
# This cell will not be graded. Feel free to alter at your wish.
R_sqr, w, b = Q5()
print(f'y = {w[0]:.3f} x0 + {w[1]:.3f} x1 + {b:.3f}')
print(f'R square = {R_sqr:.3f}')

b = [8.78937886]
R_train = 0.15117975352646185
R_test = 0.26791188864550297


TypeError: cannot unpack non-iterable NoneType object

### <span style="color:red">Question 6:</span> Asymetric random matrix (15 pts)
Write a function `asymRandomMtx(n)` that returns a $n \times n$ numpy array which is a random anti-symmetric matrix. (That is, $a_{ij}=-a_{ji}$ where $a_{kl}$ denotes the element at the $k$-th row and $l$-th column)

<span style="color:green"> <b>Examples:</b></span>
```python
asymRandomMtx(4)
```
A possible answer might be
```python
array([[ 0,  1,  0, -1],
       [-1,  0,  0,  1],
       [ 0,  0,  0, -1],
       [ 1, -1,  1,  0]])
```

In [35]:
# Please write your code here. Remember to remove the pass statement.
# Reference(建立對稱矩陣): https://codertw.com/程式語言/363766/
def asymRandomMtx(n):
    X = np.random.rand(n**2).reshape(n, n) #輸入矩陣大小與隨機值
    X = np.triu(X) #保留上三角矩陣的部分
    X_T = X.T - np.diag(X.diagonal()) #將上三角複製到下三角部分
    print(X+(-X_T)) #將下三角變號
asymRandomMtx(4)

[[ 0.80981255  0.87217591  0.9646476   0.72368535]
 [-0.87217591  0.71745362  0.46759901  0.32558468]
 [-0.9646476  -0.46759901  0.99401459  0.67687371]
 [-0.72368535 -0.32558468 -0.67687371  0.80037024]]


In [36]:
# This cell will not be graded. Feel free to alter at your wish.
np.random.seed(12345)
asymRandomMtx(4)

[[ 0.92961609  0.31637555  0.18391881  0.20456028]
 [-0.31637555  0.5955447   0.96451452  0.6531771 ]
 [-0.18391881 -0.96451452  0.74771481  0.96130674]
 [-0.20456028 -0.6531771  -0.96130674  0.65641118]]


### <span style="color:red">Question 7:</span> Solving system of linear equations (20 pts)

Solve $x_1$, $x_2$, $x_3$ that satisfy the following system of equations:
$$\left[\begin{array}{cc}  0.9344 & 0.0958\\ 0.0958 & 0.8599 \end{array}\right]^{10}
 \left[\begin{array}{c} -1.1916 x_1 + 0.1397 x_2 -1.8054 x_3\\ -0.8549 x_1 + 0.03040 x_2 -0.9211 x_3\end{array}\right]
= \left[\begin{array}{c}  1.9890 \\ 1.3183 \end{array}\right]$$

$$1.1441 x_1 -0.1975 x_2 + 0.2262 x_3 = 0.3270$$

- Hint: `numpy.concatenate`.

<span style="color:green"> <b>Examples:</b></span>
```python
x = Q6()
print(f'x1 = {x[0]:.4f}, x2 = {x[1]:.4f}, x3 = {x[2]:.4f}')
```

Should result in
```python
x1 = 0.3861, x2 = -1.1920, x3 = -1.5478
```

In [37]:
# Please write your code here. Remember to remove the pass statement.
# Reference(解三元一次方程式): https://blog.csdn.net/Meereen/article/details/105807011
def Q7():
    from scipy import linalg
    obj1 = np.array([[0.9344,0.0958],[0.0958,0.8599]])
    obj2 = np.power(obj1,10)
    #obj2[0][0]*(-1.1916*x1+0.1397*x2-1.8054*x3)+obj2[0][1]*(-0.8549*x1+0.03040*x2-0.9211*x3)=1.9890
    x1 = obj2[0][0]*(-1.1916)+obj2[0][1]*(-0.8549)
    x2 = obj2[0][0]*(0.1397)+obj2[0][1]*(0.0304)
    x3 = obj2[0][0]*(-1.8054)+obj2[0][1]*(-0.9211)
    #obj2[1][0]*(-1.1916*x1+0.1397*x2-1.8054*x3)+obj2[1][1]*(-0.8549*x1+0.03040*x2-0.9211*x3)=1.3183
    y1 = obj2[1][0]*(-1.1916)+obj2[1][1]*(-0.8549)
    y2 = obj2[1][0]*(0.1397)+obj2[1][1]*(0.0304)
    y3 = obj2[1][0]*(-1.8054)+obj2[1][1]*(-0.9211)
    a = np.array([[1.1441,-0.1975,0.2262],[x1,x2,x3],[y1,y2,y3]])
    b = np.array([0.3270,1.9890,1.3183])
    x = linalg.solve(a,b)
    print(f'x1 = {x[0]:.4f}, x2 = {x[1]:.4f}, x3 = {x[2]:.4f}')
Q7()

x1 = -7.9900, x2 = -48.7045, x3 = -0.6665


In [38]:
#check 1.1441x1 - 0.1975x2 + 0.2262x3 = 0.3270
1.1441*(-7.9900) - 0.1975*(-48.7045) + 0.2262*(-0.6665)

0.3270174500000016

### <span style="color:red">Question 8:</span> Three random walkers (25 pts)

*Ada*, *Chris*, *Jill*, *Leon*, and *Wesker* are drunk, and each of them independently performs random walk of `nsteps` steps among a straint line of integer points 

$...,-3,-2,-1,0,1,2,3,...$

Suppose they initially start from various locations, we are interested in knowing who will endup in the right-most position after a fixed steps of random walk. 

Denote integer $X_i^{(t)}$ as the position at which person $i$ stands at time $t$, then for the next time step $t+1$ he/she will take one among the three following actions with equal probability ($1/3$ each):

* Step forward:  $X_i^{(t+1)} = X_i^{(t)}+1$
* Step backward: $X_i^{(t+1)} = X_i^{(t)}-1$
* Not moving:    $X_i^{(t+1)} = X_i^{(t)}$

Write a function `drunk_race(offset, nwalks, nsteps)` that simulates `nwalks` trials, where in each trial each person $i$ starts from $X_i^{(0)}=$ `offset[i]` and independently performs the aforementioned random walk for $T=$ `nsteps` steps. The output will be a pandas series indicating, for each person $i$, how many times among those `nwalks` trials does he/she end up at the right most position (i.e., $X_i^{(T)} = \max_j X_j^{(T)}$) after random walk.

<span style="color:green"> <b>Examples:</b></span>
```python
nwalks = 5000
nsteps = 1000
players = ['Chris','Jill','Leon','Wesker','Ada']
offset = pd.Series([0,10,20,30,40], index = players)

wins = drunk_race(offset, nwalks, nsteps)
print(f'Among {nwalks} trials of {nsteps}-step random walks:')
for player in players:
    print(f'{player:10s} starts at {offset[player]:3d} and ends up at the right-most in {wins[player]:5d} trials ({100*wins[player]/nwalks:2.2f} %)')
```
Might result in
```python
Among 5000 trials of 1000-step random walks:
Chris      starts at   0 and ends up at the right-most in   204 trials (4.08 %)
Jill       starts at  10 and ends up at the right-most in   431 trials (8.62 %)
Leon       starts at  20 and ends up at the right-most in   777 trials (15.54 %)
Wesker     starts at  30 and ends up at the right-most in  1394 trials (27.88 %)
Ada        starts at  40 and ends up at the right-most in  2285 trials (45.70 %)
```

* Due to randomness the percentages may fluctuate a little bit.
* Due to the occasional ties (two or more people ending up at the same rightmost position), the percentages may total over 100%.

In [39]:
# Please write your code here. Remember to remove the pass statement.
def drunk_race(offset, nwalks = 5000, nsteps = 1000):
    pass

In [40]:
# This cell will not be graded. Feel free to alter at your wish.
np.random.seed(12345)
nwalks = 5000
nsteps = 1000
players = ['Chris','Jill','Leon','Wesker','Ada']
offset = pd.Series([0,10,20,30,40], index = players)

wins = drunk_race(offset, nwalks, nsteps)
print(f'Among {nwalks} trials of {nsteps}-step random walks:')
for player in players:
    print(f'{player:10s} starts at {offset[player]:3d} and ends up at the right-most in {wins[player]:5d} trials ({100*wins[player]/nwalks:2.2f} %)')

Among 5000 trials of 1000-step random walks:


TypeError: 'NoneType' object is not subscriptable