<div style="text-align:center;color:#888888;"><h2> IMP 5001 - Introduction to Medical Informatics </h2></div>
<div style="text-align:center;"><h1> Final Exam (109-1) </h1></div>

* Exam date: 2021/01/14 9:10-12:10
* There are 8 questions, 100 points in total.
* Open everything including the Internet. Feel free to import any package you need.
* "Cheating" is basically coordinating with others. So don't do that.
* When you find necessary to raise an exception, please include a meaningful error message to indicate what the source of the error is.

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
from IPython.display import Image
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import numpy as np
import pandas as pd 

In this exam, you are given a data set in <b>data/diabetes.csv</b>, where the data attributes are described as follows: (all numeric-valued)

* <b>Pregnancies</b> - Number of times pregnant
* <b>Glucose</b> - Plasma glucose concentration a 2 hours in an oral glucose tolerance test
* <b>BloodPressure</b> - Diastolic blood pressure (mm Hg)
* <b>SkinThickness</b> - Triceps skin fold thickness (mm
* <b>Insulin</b> - 2-Hour serum insulin (mu U/ml)
* <b>BMI</b> - Body mass index (weight in kg/(height in m)^2)
* <b>DiabetesPedigreeFunction</b> - Diabetes pedigree function
* <b>Age</b> - Age (years)
* <b>TestResult</b> - Class variable (0 or 1)

In [4]:
df = pd.read_csv("data/diabetes.csv")
df.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0           72.0           35.0      NaN  33.6   
1            1     85.0           66.0           29.0      NaN  26.6   
2            8    183.0           64.0            NaN      NaN  23.3   
3            1     89.0           66.0           23.0     94.0  28.1   
4            0    137.0           40.0           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age TestResult  
0                     0.627   50   Positive  
1                     0.351   31   Negative  
2                     0.672   32   Positive  
3                     0.167   21   Negative  
4                     2.288   33   Positive

### <span style="color:red">Question 1:</span> Separate Features and Class Labels (12 pts)

The data frame loaded from <b>data/diabetes.csv</b> contains both the features as well as the class label (i.e., the <b>TestResult</b> column).  Write a function called `separateInputOutput` that
* Separates the features and the class labels out from the data frame.
* The class labels are label-encoded as numerical values (0 and 1).
* Extract the names of the features.
* Extract the class names.

<span style="color:green"> <b>Examples:</b></span>
```python
X_orig, y, feature_names,class_names = separateInputOutput(df)
feature_names
class_names
X_orig[0:4]
y[0:4]
class_names[y][0:4]
```
Should result in
```python
array(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'], dtype=object)
array(['Negative', 'Positive'], dtype=object)
array([[6.00e+00, 1.48e+02, 7.20e+01, 3.50e+01,      nan, 3.36e+01,
        6.27e-01, 5.00e+01],
       [1.00e+00, 8.50e+01, 6.60e+01, 2.90e+01,      nan, 2.66e+01,
        3.51e-01, 3.10e+01],
       [8.00e+00, 1.83e+02, 6.40e+01,      nan,      nan, 2.33e+01,
        6.72e-01, 3.20e+01],
       [1.00e+00, 8.90e+01, 6.60e+01, 2.30e+01, 9.40e+01, 2.81e+01,
        1.67e-01, 2.10e+01]])
array([1, 0, 1, 0])
array(['Positive', 'Negative', 'Positive', 'Negative'], dtype=object)
```

In [5]:
# Question 1: Please write your code here
def separateInputOutput(df):
    pass


In [28]:
feature_names = df.iloc[0:0,:]
feature_names

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, TestResult]
Index: []

In [11]:
X_orig, y, feature_names, class_names = separateInputOutput(df)

TypeError: cannot unpack non-iterable NoneType object

In [12]:
# For testing Q1. Feel free to alter as this cell will not be graded.
feature_names
class_names
X_orig[0:4]
y[0:4]
class_names[y][0:4]

0    Empty DataFrame
Columns: [Pregnancies, Glucose...
dtype: object

array(['Negative', 'Positive'], dtype=object)

array([[6.00e+00, 1.48e+02, 7.20e+01, 3.50e+01,      nan, 3.36e+01,
        6.27e-01, 5.00e+01],
       [1.00e+00, 8.50e+01, 6.60e+01, 2.90e+01,      nan, 2.66e+01,
        3.51e-01, 3.10e+01],
       [8.00e+00, 1.83e+02, 6.40e+01,      nan,      nan, 2.33e+01,
        6.72e-01, 3.20e+01],
       [1.00e+00, 8.90e+01, 6.60e+01, 2.30e+01, 9.40e+01, 2.81e+01,
        1.67e-01, 2.10e+01]])

array([1, 0, 1, 0], dtype=int32)

array(['Positive', 'Negative', 'Positive', 'Negative'], dtype=object)

In [9]:
arch = np.load('npz/Q1.npz',allow_pickle = True)
X_orig = arch['X_orig']
y = arch['y']
feature_names = arch['feature_names']
class_names = arch['class_names']
arch.close()

### <span style="color:red">Question 2:</span> Plot Feature Histograms (12 pts)

It is important to understand the features, and the first step towards that is to visualize their distribution.  Check out the API reference [matplotlib.pyplot.hist](https://matplotlib.org/3.3.1/api/_as_gen/matplotlib.pyplot.hist.html) on the Internet, and write a function called `plotFeatureHistograms` that plots the histogram for each each feature, where each histogram has 20 bins.

<span style="color:green"> <b>Examples:</b></span>
```python
plotFeatureHistograms(df,feature_names)
```
Should result in <img src='figures/Q2.png'>

In [ ]:
# Question 2: Please write your code here
def plotFeatureHistograms(df,feature_names):
    plt.figure(figsize=(9,9))
    plt.subplots_adjust(hspace=0.35)
    for idx,feature in enumerate(feature_names):
        if idx > 8:
            break
        plt.subplot(3, 3, idx+1,title=feature)
        # Please write your code here

In [ ]:
# For testing Q2. Feel free to alter as this cell will not be graded.
plotFeatureHistograms(df,feature_names)

### <span style="color:red">Question 3:</span> Impute Missing Data (12 pts)

Some features in <b>X_orig</b> are missing and we need to impute missing data. Write a function called `imputeMissingData` that impute the missing data with the median imputing stretagy.


<span style="color:green"> <b>Examples:</b></span>
```python
X_toy = [[     6,     8,np.nan,     9],
         [     8,     3,     1,np.nan],
         [np.nan,np.nan,     9,     7],
         [     9,     0,     6,np.nan]]
imputeMissingData(X_toy)
```
Should result in
```python
array([[6., 8., 6., 9.],
       [8., 3., 1., 8.],
       [8., 3., 9., 7.],
       [9., 0., 6., 8.]])
```

In [ ]:
# Question 3: Please write your code here
def imputeMissingData(X_orig):
    import scipy.sparse as sp
    from sklearn.impute import SimpleImputer
    X = X_orig
    imp = SimpleImputer(missing_values = np.nan, strategy = 'median')
    imp.fit(X)
    print(imp.transform(X))#.toarray())

In [ ]:
# For testing Q3. Feel free to alter as this cell will not be graded.
X_toy = [[     6,     8,np.nan,     9],
         [     8,     3,     1,np.nan],
         [np.nan,np.nan,     9,     7],
         [     9,     0,     6,np.nan]]
imputeMissingData(X_toy)

In [ ]:
X_im = imputeMissingData(X_toy)

In [ ]:
arch = np.load('npz/Q3.npz',allow_pickle = True)
X_im = arch['X_im']
arch.close()

### Split the data into training and testing sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_im, y, test_size=0.3, random_state=1, stratify=y)

### <span style="color:red">Question 4:</span> Standardize Features (12 pts)

Standardization of a dataset is a common requirement for many machine learning estimators: they might behave badly if the individual features do not more or less have similar dynamic range. Check out the API reference [sklearn.preprocessing](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing) on the Internet, and write a function called `standardizeFeatures` that normalizes each feature so they have the same dynamic range.  More precisely, for any given feature, the feature value $x$ is transformed to $z = (x-l)/(u-l)$, where $l$ is the minimum feature value, and $u$ is the maximum feature value.

<span style="color:green"> <b>Examples:</b></span>
```python
X_toy = [[ 6, 8,-4, 9],
         [ 8, 3, 1,-7],
         [-7,-8, 9, 9]]
standardizeFeatures(X_toy,[[ 9, 0, 6,-7]])
```
Should result in
```python
(array([[0.86666667, 1.        , 0.        , 1.        ],
        [1.        , 0.6875    , 0.38461538, 0.        ],
        [0.        , 0.        , 1.        , 1.        ]]),
 array([[1.06666667, 0.5       , 0.76923077, 0.        ]]))
```

In [ ]:
# Question 4: Please write your code here
def standardizeFeatures(X_train,X_test):
    pass

In [ ]:
X_train_std, X_test_std = standardizeFeatures(X_train,X_test)

In [ ]:
# For testing Q4. Feel free to alter as this cell will not be graded.
X_toy = [[ 6, 8,-4, 9],
         [ 8, 3, 1,-7],
         [-7,-8, 9, 9]]
standardizeFeatures(X_toy,[[ 9, 0, 6,-7]])

In [ ]:
arch = np.load('npz/Q4.npz',allow_pickle = True)
X_train_std = arch['X_train_std']
X_test_std = arch['X_test_std']
arch.close()

### <span style="color:red">Question 5:</span> Transform Features (12 pts)

Polynomial features are a common way to represent the nonlinear interactions between features.  For instance, if an input sample is two dimensional and of the form $(a,b)$, the degree-2 polynomial features are $(1, a, b, a^2, ab, b^2)$. Check out the API reference [sklearn.preprocessing](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing) on the Internet, and write a function called `PolynomialFeatures` that generates new feature matrices consisting of all polynomial combinations of the features with degree at most 2, for both the training and testing data.

<span style="color:green"> <b>Examples:</b></span>
```python
transformFeatures(np.array([[2,3],[5,7]]), np.array([[-2,5]]))
```
Should result in
```python
(array([[ 1.,  2.,  3.,  4.,  6.,  9.],
        [ 1.,  5.,  7., 25., 35., 49.]]),
 array([[  1.,  -2.,   5.,   4., -10.,  25.]]))
```

In [ ]:
# Question 5: Please write your code here
def transformFeatures(X_train_std, X_test_std):
    pass

In [ ]:
# For testing Q5. Feel free to alter as this cell will not be graded.
transformFeatures(np.array([[2,3],[5,7]]), np.array([[-2,5]]))

In [ ]:
X_train_poly, X_test_poly = transformFeatures(X_train_std,X_test_std)

In [ ]:
arch = np.load('npz/Q5.npz',allow_pickle = True)
X_train_poly = arch['X_train_poly']
X_test_poly = arch['X_test_poly']
arch.close()

### <span style="color:red">Question 6:</span> Linear Discriminant Analysis and Visualize (14 pts)

You might be wondering if the extracted features are good enough to separate the various classes. A common trick is to apply Linear discriminant analysis (LDA) so that each data point is represented by just a scalar, to which one may plot the histogram of those scalar representation of data point for each class. Write a function called `LDAVisualize` that performs LDA and reduce feature dimension to 1, and then plot the histogram of the (dimension-reduced) data for each class.

<span style="color:green"> <b>Examples:</b></span>
```python
X_toy = np.array([[0,0],[0,1],[0,2],[0,3],[0,4],[0,5],[1,1],[1,4],[2,0],[2,1],[2,2],[2,3],[2,4],[2,5]])
y_toy = np.array([    0,    0,    0,    1,    1,    1,    0,    1,    0,    0,    0,    1,    1,    1])
LDAVisualize(X_toy,y_toy,class_names)
```
Should result in
```python
array([[-3.06186218],
       [-1.83711731],
       [-0.61237244],
       [ 0.61237244],
       [ 1.83711731],
       [ 3.06186218],
       [-1.83711731],
       [ 1.83711731],
       [-3.06186218],
       [-1.83711731],
       [-0.61237244],
       [ 0.61237244],
       [ 1.83711731],
       [ 3.06186218]])
```
<img src="figures/Q6.png">

In [ ]:
# Question 6: Please write your code here
def LDAVisualize(X,y,class_names):
    # Write your code here
    plt.figure(figsize=(8,4))
    for i in range(len(class_names)):
        plt.subplot(1, 2, i+1,title=class_names[i])
        # Write your code here
    return X_lda

In [ ]:
# For testing Q6. Feel free to alter as this cell will not be graded.
X_toy = np.array([[0,0],[0,1],[0,2],[0,3],[0,4],[0,5],[1,1],[1,4],[2,0],[2,1],[2,2],[2,3],[2,4],[2,5]])
y_toy = np.array([    0,    0,    0,    1,    1,    1,    0,    1,    0,    0,    0,    1,    1,    1])
LDAVisualize(X_toy,y_toy,class_names)

In [ ]:
X_train_lda = LDAVisualize(X_train_std,y_train,class_names)

In [ ]:
arch = np.load('npz/Q6.npz',allow_pickle = True)
X_train_lda = arch['X_train_lda']
arch.close()

### <span style="color:red">Question 7:</span> K Nearest Neighbor With Additional Settings (12 pts)

K-nearest neighbors (KNN) is a simple and effective tool for classification problems.  Check out the API reference [sklearn.neighbors.KNeighborsClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html) on the Internet, and write a function called `myKNN` that returns a KNN model which

* Classifies a query point based on its 3 nearest neighbors.
* The neighbors do not vote equally, instead their votes are weighted inversely proportional to their distance.  In other words, closer neighbors of a query point will have a greater influence than neighbors which are further away.
* The distance between two $m$-dimensional points ${\bf u} = (u_1,...,u_m)$ and ${\bf v} = (v_1,...,v_m)$ is computed as
$$d({\bf u},{\bf v}) = \sum_{i=1}^m |u_i-v_i|$$

<span style="color:green"> <b>Examples:</b></span>
```python
X_toy = [[0],[1],[2],[3],[4],[5],[6],[7],[8]]
y_toy = [0,0,0,0,0,1,1,1,0]
knn_toy = myKNN()
knn_toy.fit(X_toy,y_toy)
z_toy = knn_toy.predict_proba([[3.6],[5.2]])
```
Then the value for <b>z_toy</b> should be
```python
array([[0.85365854, 0.14634146],
       [0.11764706, 0.88235294]])
```

In [ ]:
# Question 7: Please write your code here
def myKNN():
    pass

In [ ]:
# For testing Q7. Feel free to alter as this cell will not be graded.
X_toy = [[0],[1],[2],[3],[4],[5],[6],[7],[8]]
y_toy = [0,0,0,0,0,1,1,1,0]
knn_toy = myKNN()
knn_toy.fit(X_toy,y_toy)
z_toy = knn_toy.predict_proba([[3.6],[5.2]])
z_toy

In [ ]:
knn = myKNN()
knn.fit(X_train_std, y_train)
Z_test = knn.predict_proba(X_test_std)

In [ ]:
arch = np.load('npz/Q7.npz',allow_pickle = True)
Z_test = arch['Z_test']
arch.close()

### <span style="color:red">Question 8:</span> K Nearest Neighbor With Weighted Classes (14 pts)

A common stretagy towards imbalanced dataset is to assign class-dependent weights to each data point. In that case, the data points of the majority class will be assigned less weights then that of the minority class.

For instace, consider a KNN model constructed and trained by
```python
X_toy = [[0],[1],[2],[3],[4],[5],[6],[7],[8],[9]]
y_toy = [0,0,0,0,0,1,1,1,0,1]
knn_toy = KNeighborsClassifier(n_neighbors=4)
knn_toy.fit(X_toy,y_toy)
```
For query point $3.6$, the KNN model will find its four nearest neighbors as follows:

| <!-- --> | <!-- --> |
| --- | --- |
| <b>Neighbor point</b> | <b>Neighbor label</b> |
| 4.0  | 0    |
| 3.0  | 0    |
| 5.0  | 1    |
| 2.0  | 0    |

Among the four neighbors, 3 (=75%) belongs to class 0, and 1 (=25%) belongs to class 1.  Hence if one computes
```python
knn_toy.predict_proba([[3.6]])
```
It will return
```python
array([[0.75, 0.25]])
```

Suppose now for each data point we assign weights inversely proportional to the portion of class it belongs to. That is, as there are 6 (=60%) data points belonging to class 0, and 4 (=40%) data points belonging to class 1, the weights of the four nearest neighbors of query point $3.6$ are given by

| <!-- --> | <!-- --> | <!-- --> |
| --- | --- | --- |
| <b>Neighbor point</b> | <b>Neighbor label</b> | <b>Neighbor Weight</b>|
| 4.0  | 0 | $1/0.6 \approx 1.67$ |
| 3.0  | 0 | $1/0.6 \approx 1.67$ |
| 5.0  | 1 | $1/0.4 = 2.5$ |
| 2.0  | 0 | $1/0.6 \approx 1.67$ |

Under such circumstances, we say the query point has a "portion" of $\frac{3/0.6}{3/0.6 + 1/0.4} \approx 0.67$ belonging to class 0, and a "portion" of $\frac{1/0.4}{3/0.6 + 1/0.4} \approx 0.33$ belonging to class 1.

Write a function called `classWeightAdjustedProba` that, when given a KNN model, the class weights, and query points, will return the portions of each query point beloning to each class.

<span style="color:green"> <b>Examples:</b></span>
```python
X_toy = [[0],[1],[2],[3],[4],[5],[6],[7],[8],[9]]
y_toy = [0,0,0,0,0,1,1,1,0,1]
knn_toy = KNeighborsClassifier(n_neighbors=4)
knn_toy.fit(X_toy,y_toy)
knn_toy.predict_proba([[3.6],[5.2]])
classWeightAdjustedProba(knn_toy,len(y_toy)/np.bincount(y_toy),[[3.6],[5.2]])
```
Should result in
```python
KNeighborsClassifier(n_neighbors=4)
array([[0.75, 0.25],
       [0.25, 0.75]])
array([[0.66666667, 0.33333333],
       [0.18181818, 0.81818182]])
```

In [ ]:
# Question 8: Please write your code here
def classWeightAdjustedProba(model,class_weight,X_test):
    pass

In [ ]:
# For testing Q8. Feel free to alter as this cell will not be graded.
X_toy = [[0],[1],[2],[3],[4],[5],[6],[7],[8],[9]]
y_toy = [0,0,0,0,0,1,1,1,0,1]
knn_toy = KNeighborsClassifier(n_neighbors=4)
knn_toy.fit(X_toy,y_toy)
knn_toy.predict_proba([[3.6],[5.2]])
classWeightAdjustedProba(knn_toy,len(y_toy)/np.bincount(y_toy),[[3.6],[5.2]])